// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleApplication.Models;

namespace PeopleApplication.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20211222161123_CreatePersonDb1")]
    partial class CreatePersonDb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleApplication.Models.Cities", b =>
                {
                    b.Property<int>("CityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityNmae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CtryCode")
                        .HasColumnType("int");

                    b.HasKey("CityCode");

                    b.HasIndex("CtryCode");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("PeopleApplication.Models.Country", b =>
                {
                    b.Property<int>("CrtyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CrtyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrtyCode");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("PeopleApplication.Models.Person", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pid");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("PeopleApplication.Models.Cities", b =>
                {
                    b.HasOne("PeopleApplication.Models.Country", "country")
                        .WithMany("cityinfo")
                        .HasForeignKey("CtryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
